// Generated by CoffeeScript 1.8.0
(function() {
  var executeContent, new_url, old_url;

  old_url = '';

  new_url = '';

  if (window.urlWatchInterval) {
    clearInterval(window.urlWatchInterval);
  }

  window.urlWatchInterval = setInterval((function() {
    new_url = window.location.href;
    if (old_url !== new_url) {
      if (executeContent()) {
        return old_url = new_url;
      }
    }
  }), 1000);

  executeContent = function() {
    var a, coffeescript, div, h1, h3, iframe, img, inject_key, input, link, markNew, markUnread, old_entry, p, page, parseQueryString, pathname, per_page, query, query_str, raw, repo, script, span, teacup, url, _ref, _ref1;
    console.log('CONTENT EXECUTED');
    parseQueryString = function() {
      var objURL, str;
      str = window.location.search;
      objURL = {};
      str.replace(new RegExp('([^?=&]+)(=([^&]*))?', 'g'), function($0, $1, $2, $3) {
        objURL[$1] = $3;
      });
      return objURL;
    };
    markNew = function(ticket, difference) {
      var $el;
      console.log('NEW');
      $el = $("li[data-issue-id='" + ticket + "']");
      return $el.find('.issue-title').append("<span class = 'new-comments' style= 'color:purple;'>\n  " + difference + " new comments\n</span>");
    };
    markUnread = function(ticket) {
      var $el;
      console.log('NEW');
      $el = $("li[data-issue-id='" + ticket + "']");
      return $el.find('.issue-title').append("<span class = 'new-comments' style= 'color:green;'>\n  unread ticket\n</span>");
    };
    teacup = window.window.teacup;
    span = teacup.span, div = teacup.div, a = teacup.a, h1 = teacup.h1, h3 = teacup.h3, p = teacup.p, iframe = teacup.iframe, raw = teacup.raw, script = teacup.script, coffeescript = teacup.coffeescript, link = teacup.link, input = teacup.input, img = teacup.img;
    old_entry = null;
    url = parseQueryString();
    console.log(localStorage);
    pathname = new URL(window.location.href).pathname;
    if (/issues$|pulls$/.test(pathname)) {
      if (!((_ref = $('#js-issues-search')) != null ? _ref.length : void 0)) {
        return false;
      }
      console.log('ISSUES PAGE FOUND');
      query = $('#js-issues-search').val();
      repo = $('head > meta[property="og:title"]').attr('content');
      query = query.replace(/\s/g, '+');
      query_str = "" + query;
      per_page = $('[data-issue-id]').length;
      page = url.page || '1';
      chrome.runtime.sendMessage({
        type: 'search-info',
        query: query_str,
        repo: repo,
        page: page,
        per_page: per_page
      }, function(data) {
        var comments, item, num, _i, _len, _ref1, _results;
        console.log(data != null ? data.items : void 0, 'panda');
        _ref1 = (data != null ? data.items : void 0) || [];
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          item = _ref1[_i];
          $("li[data-issue-id='" + item.number + "'] .new-comments").remove();
          if (!localStorage[item.html_url]) {
            console.log('new?');
            markUnread(item.number);
            continue;
          }
          comments = item.comments + 1;
          num = parseInt(localStorage[item.html_url]);
          console.log(num, comments, 'panda');
          if (num < comments) {
            _results.push(markNew(item.number, comments - num));
          } else if (num > comments) {
            _results.push(localStorage[item.html_url] = comments);
          } else {
            _results.push(console.log('do nothing they are equal'));
          }
        }
        return _results;
      });
      return true;
    } else if (/issues\/\d+$|pull\/\d+$/.test(pathname)) {
      if (!((_ref1 = $('.timeline-comment-wrapper > .comment')) != null ? _ref1.length : void 0)) {
        return false;
      }
      console.log('TICKET FOUND');
      inject_key = (function(_this) {
        return function() {
          var comments, key, _ref2;
          key = window.location.href;
          comments = (_ref2 = $('.timeline-comment-wrapper > .comment')) != null ? _ref2.length : void 0;
          console.log(key, comments, 'SET');
          return localStorage[key] = comments;
        };
      })(this);
      inject_key();
      window.addEventListener("beforeunload", function(e) {
        return inject_key();
      });
      return true;
    } else {
      return true;
    }
  };

}).call(this);
