// Generated by CoffeeScript 1.8.0
(function() {
  var renderUser;

  renderUser = function() {
    return chrome.runtime.sendMessage({
      type: 'user-info',
      interactive: false
    }, function(user_info) {
      if (!user_info.error) {
        $('#signin').hide();
        $('#revoke').show();
        return $('#user').html("<div>\n  <span class=\"name\">Logged in as: " + user_info.login + "</span>\n  <img src=\"" + user_info.avatar_url + "\"/>\n</div>");
      } else {
        $('#signin').show();
        $('#revoke').hide();
        return $('#user').html("<div>\n  <span class=\"name\">Error detected: </span>\n  <span class=\"error\">" + user_info.error + "</span>\n</div>");
      }
    });
  };

  $(document).ready(function() {
    return gh.tokenFetcher.getToken(false, function(error, access_token) {
      console.log(access_token, 'PANDA');
      $('#signin').on('click', function(e) {
        return gh.interactiveSignIn(function() {
          $('#signin').hide();
          $('#revoke').show();
          chrome.browserAction.setIcon({
            path: "github-good.png"
          });
          return renderUser();
        });
      });
      $('#revoke').on('click', function(e) {
        gh.revokeToken();
        $('#user').empty();
        $('#signin').show();
        return $('#revoke').hide();
      });
      if (access_token) {
        $('#user').empty();
        $('#signin').hide();
        $('#revoke').show();
        return renderUser();
      } else {
        $('#user').empty();
        $('#signin').show();
        return $('#revoke').hide();
      }
    });
  });

}).call(this);
