// Generated by CoffeeScript 1.8.0
(function() {
  gh.tokenFetcher.getToken(true, function(error, access_token) {
    var revoke_button, signin_button;
    signin_button = document.querySelector('#signin');
    if (signin_button != null) {
      signin_button.onclick = gh.interactiveSignIn;
    }
    revoke_button = document.querySelector('#revoke');
    if (revoke_button != null) {
      revoke_button.onclick = gh.revokeToken;
    }
    return chrome.runtime.sendMessage({
      type: 'user-info',
      interactive: false
    }, function(user_info) {
      if (!user_info.error) {
        $('#signin').hide();
        $('#revoke').show();
        return $('#user').html("<div>\n  <span class=\"name\">Logged in as: " + user_info.login + "</span>\n  <img src=\"" + user_info.avatar_url + "\"/>\n</div>");
      } else {
        $('#signin').show();
        $('#revoke').hide();
        return $('#user').html("<div>\n  <span class=\"name\">Error detected: </span>\n  <span class=\"error\">" + user_info.error + "</span>\n</div>");
      }
    });
  });

}).call(this);
